#!/bin/bash

#	priest:	Hope that firewall works because your screwed

#	Tested: Debian 10.7

if [ $# -lt 1 ]; then
	echo 'Usage: ./initialize_target target.com'
	exit 1
fi

# userid=`id -u`

# if [ "${userid}" != '0' ]; then
# 	echo 'Usage Error: You must run this script with root privileges'
# 	exit 1
# fi

if [ ! -d "~/workspace/rawdata/$1" ]; then

	mkdir -p ~/workspace/rawdata/$1
	mkdir -p ~/workspace/rawdata/$1/nmap-data
	mkdir -p ~/workspace/rawdata/$1/split
	cd ~/workspace/rawdata/$1

else
	echo "[*]	~/workspace/rawdata/$1 Exists: Exiting!"
	exit 1
fi

#-------------------------------------------------------------------------------------------------------------------------------------------
#		AMASS -- Bulk collection of target HOSTNAMES list
#-------------------------------------------------------------------------------------------------------------------------------------------
#		amass .json output currently malfunctioning

echo "[*]	Gathering bulk list of domains with amass"
amass enum -passive -noalts -norecursive -o ~/workspace/rawdata/$1/$1-bulk-HOSTNAMES.lst -d $1
#jq -r '.name' $1.json | sed 's/\"//g' | sed 's/\*\.//g' > $1-bulk-HOSTNAMES.lst
wc -l $1-bulk-HOSTNAMES.lst
echo -e "\n"

#-------------------------------------------------------------------------------------------------------------------------------------------
#		HTTPROBE -- Detect live 80, 443 services
#-------------------------------------------------------------------------------------------------------------------------------------------

echo "[*]	Probing $1-bulk-HOSTNAMES.lst with httprobe"
cat $1-bulk-HOSTNAMES.lst | httprobe -c 60 | tee -a $1-bulk-80-443-HOSTNAMES.tmp 
cat $1-bulk-80-443-HOSTNAMES.tmp | awk -F 'http://' '{print $2}' | cut -d ':' -f 1 | sort -u | sed '1d' > $1-80-HOSTNAMES.lst
cat $1-bulk-80-443-HOSTNAMES.tmp | awk -F 'https://' '{print $2}' | cut -d ':' -f 1 | sort -u | sed '1d' > $1-443-HOSTNAMES.lst
cat $1-80-HOSTNAMES.lst > $1-bulk-80-443-HOSTNAMES.lst
cat $1-443-HOSTNAMES.lst >> $1-bulk-80-443-HOSTNAMES.lst
rm -rf $1-bulk-80-443-HOSTNAMES.tmp
echo -e "\n"

#-------------------------------------------------------------------------------------------------------------------------------------------
#		MASSDNS -- Convert HOSTNAMES.lst's to IP
#-------------------------------------------------------------------------------------------------------------------------------------------

echo "[*]	Converting $1-80-HOSTNAMES.lst to IP"
sudo massdns -r ~/workspace/tools/massdns/lists/resolvers.txt -t A -o S -w massdns-results.txt $1-80-HOSTNAMES.lst
grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" massdns-results.txt | sort -u > $1-80-IPs.lst
sudo rm -rf massdns-results.txt

echo "[*]	Converting $1-443-HOSTNAMES.lst to IP"
sudo massdns -r ~/workspace/tools/massdns/lists/resolvers.txt -t A -o S -w massdns-results.txt $1-443-HOSTNAMES.lst
grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" massdns-results.txt | sort -u > $1-443-IPs.lst
sudo -rf rm massdns-results.txt

echo "[*]	Converting $1-bulk-80-443-HOSTNAMES.lst to IP"
sudo massdns -r ~/workspace/tools/massdns/lists/resolvers.txt -t A -o S -w massdns-results.txt $1-bulk-80-443-HOSTNAMES.lst
grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" massdns-results.txt | sort -u > $1-bulk-80-443-IPs.lst
sudo -rf rm massdns-results.txt

echo "[*]	Converting $1-bulk-HOSTNAMES.lst to IP"
sudo massdns -r ~/workspace/tools/massdns/lists/resolvers.txt -t A -o S -w massdns-results.txt $1-bulk-HOSTNAMES.lst
grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" massdns-results.txt | sort -u > $1-bulk-IPs.lst
sudo rm -rf massdns-results.txt
echo -e "\n"

#-------------------------------------------------------------------------------------------------------------------------------------------
#		MASSCAN -- TOP 2000 service ports per detected live 80, 443 IPs
#-------------------------------------------------------------------------------------------------------------------------------------------
#		Define suitable output for results/searching ie: json, xml, list etc..

echo "[*]	Probing $1-bulk-80-443-IPs.lst TOP 2000 ports with masscan"
sudo masscan -iL $1-bulk-80-443-IPs.lst --rate=1000 --banners --source-port 61000 -p `cat /usr/share/nmap/nmap-services | grep -i tcp | sort -k 3 -n -r | awk '{print $2}' | cut -d "/" -f1 | head -2000 | tr '\n' "," | sed 's/,$//'` --excludefile ~/workspace/tools/masscan/data/exclude.conf --output-format binary --output-filename $1-bulk-80-443-MASSCAN.bin
sudo masscan --readscan $1-bulk-80-443-MASSCAN.bin -oJ targets-banners-2000-ports.json
echo -e "\n"

#-------------------------------------------------------------------------------------------------------------------------------------------
#		NMAP -- Versioning, banner, vulners, http-vulners-regex, http-headers | ToDo: asn-query
#-------------------------------------------------------------------------------------------------------------------------------------------
#		.json output parsing depends on masscan source: git, apt-get. Check: sed '1d;$d'

echo "[*]	Probing IPs & Ports via nmap: Versioning, banners, vulners, http-vulners-regex, http-headers"
cat targets-banners-2000-ports.json | awk '{print $3 $9}' | tr -d , | tr '"' " " | sort -u | sed '1d' | awk '{print "nmap -p "  $2" "  $1 " -sV -oX nmap-data/"$1"-result-"$2".xml --script=banner --host-timeout 55 -vvv -Pn -R --script=vulners --script=http-vulners-regex --script=http-headers"}' | sort -u | sort -R > nmap-scan.txt

IFS=$'\n'                                                                                                               # make newlines the only separator

# sudo rm -rf split/*-ScanTarget                                                                                        # cleanup
# sudo rm -rf nmap-data/*.xml                                                                                           # cleanup

split -l 30 --additional-suffix=-ScanTarget nmap-scan.txt                                                               # split the nmap commands into smaller batches

mv *-ScanTarget split/                                                                                                  # move split files, from PWD to split/

for file in $(ls split/*-ScanTarget); do sleep 60 && for target in $(cat $file); do sh -c "sudo $target" & done ; done  # run each splitted file (contains 30 nmap commands) and wait for 60 seconds until the next batch

echo -e "\n"

sleep 60

echo "[*]	Formatting nmap-data/ output"
for file in $(ls nmap-data/); do xsltproc nmap-data/$file -o nmap-data/$file.html; done
mkdir -p ~/workspace/rawdata/$1/nmap-data/xml	# searchsploit --nmap *.xml
sudo mv nmap-data/*.xml nmap-data/xml
sleep 10
echo -e "\n"

#-------------------------------------------------------------------------------------------------------------------------------------------
#		EYEWITNESS --all-protocols || --web (Default)
#-------------------------------------------------------------------------------------------------------------------------------------------

echo "[*]	Running EyeWitness: $1-bulk-80-443-HOSTNAMES.lst --web" 
python3 ~/workspace/tools/EyeWitness/Python/EyeWitness.py --prepend-https -f $1-bulk-80-443-HOSTNAMES.lst -d $PWD/eyewitness --no-prompt --timeout 120 --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
echo -e "\n"


#-------------------------------------------------------------------------------------------------------------------------------------------
#		ANALYZE -- Set user permissions .. id || id -u
#-------------------------------------------------------------------------------------------------------------------------------------------

find ~/workspace/rawdata/$1 -type d -print0 | xargs -0 sudo chown -R user:user

echo -e "[*] Finished Target Initialization\n\n"



